@echo off
echo Starting Cracker Demo local development environment...
echo Opening browser...
start http://127.0.0.1:9000
"%~dp0.tools\php\php.exe" -c "%~dp0.tools\php\php.ini" "%~dp0artisan" serve --port=9000
